version: "3.8"

services:
  todoist-scheduler:
    image: ghcr.io/iloveitaly/todoist-scheduler:latest
    restart: always
    env_file: env-todoist
    environment:
      - SCHEDULE=0 0 * * *
    volumes:
      # copy the local filter JSON config into the container
      - ./scheduler_filters.json:/app/filters.json
