[tools]
python = "3.14"

uv = "latest"
direnv = "latest"
gitleaks = "latest"
"github:casey/just" = "latest"

[bootstrap.packages]
"apt:zsh" = { os = "linux" }

[settings]
python.uv_venv_auto = "create|source"
